# -*- coding: utf-8 -*-
"""Plagiarism Checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhbP1tzrp9JaupTWLRlNrWwiVDDyRxab
"""

!pip install spacy
!python -m spacy download en_core_web_sm

import spacy
from difflib import SequenceMatcher

nlp = spacy.load("en_core_web_sm")

def preprocess_text(text):
    """Preprocess text: tokenize, remove stopwords, and lemmatize."""
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]
    return " ".join(tokens)

def calculate_similarity(text1, text2):
    """Calculate similarity between two texts using SequenceMatcher."""
    return SequenceMatcher(None, text1, text2).ratio()


text1 = input("Enter the first text: ")
text2 = input("Enter the second text: ")


preprocessed_text1 = preprocess_text(text1)
preprocessed_text2 = preprocess_text(text2)


similarity_score = calculate_similarity(preprocessed_text1, preprocessed_text2)
similarity_percentage = similarity_score * 100


print(f"\nSimilarity Score: {similarity_percentage:.2f}%")
if similarity_percentage > 80:
    print("⚠️ High similarity detected! Possible plagiarism.")
else:
    print("✅ Low similarity detected. No plagiarism.")